- name: variables from play level
  hosts: web
  vars:
    course: "Devops"
    City : "bangalore"
    year : "2025"
  tasks:
  - name: check variables 
    ansible.builtin.debug:
      msg: "Hi,i am learning {{Course}} in {{city}} since {{year}}"