- name: variables from play level
  hosts: web
  vars_files:
   - variables.yaml 
  tasks:
  - name: check variables 
    ansible.builtin.debug:
      msg: "Hi,i am doing my graduation {{ Course }} in {{ City }} since {{ Year }}"